"""add missing columns to model_versions

Revision ID: 8145fdcd9bdd
Revises: 86c3434a7981
Create Date: 2026-07-07 20:30:19.510794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8145fdcd9bdd'
down_revision: Union[str, Sequence[str], None] = '86c3434a7981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_models_model_id'), table_name='scene_models')
    op.drop_index(op.f('ix_scene_models_scene_id'), table_name='scene_models')
    op.drop_table('scene_models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    # 先添加可空的列
    op.add_column('model_versions', sa.Column('scene_id', sa.Integer(), nullable=True, comment='所属场景'))
    op.add_column('model_versions', sa.Column('model_name', sa.String(length=100), nullable=True, comment='模型名称'))
    op.add_column('model_versions', sa.Column('model_type', sa.String(length=50), nullable=True, comment='模型类型：yolov11n/s/m/l/x'))
    # 更新现有数据：为 model_versions 设置默认值
    op.execute("UPDATE model_versions SET scene_id = 5, model_name = 'yolo11n', model_type = 'yolov11n' WHERE scene_id IS NULL")
    # 设置为非空
    op.alter_column('model_versions', 'scene_id', nullable=False)
    op.alter_column('model_versions', 'model_name', nullable=False)
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.create_index(op.f('ix_model_versions_scene_id'), 'model_versions', ['scene_id'], unique=False)
    op.create_foreign_key(None, 'model_versions', 'detection_scenes', ['scene_id'], ['id'])
    op.drop_column('model_versions', 'model_id')
    op.drop_column('model_versions', 'source')
    # 先添加可空的列
    op.add_column('training_tasks', sa.Column('scene_id', sa.Integer(), nullable=True, comment='关联场景'))
    op.add_column('training_tasks', sa.Column('model_name', sa.String(length=50), nullable=True, comment='基础模型：yolov11n/s/m/l/x'))
    # 更新现有数据
    op.execute("UPDATE training_tasks SET scene_id = 5, model_name = 'yolov11n' WHERE scene_id IS NULL")
    # 设置为非空
    op.alter_column('training_tasks', 'scene_id', nullable=False)
    op.drop_index(op.f('ix_training_tasks_model_id'), table_name='training_tasks')
    op.create_index(op.f('ix_training_tasks_scene_id'), 'training_tasks', ['scene_id'], unique=False)
    op.create_foreign_key(None, 'training_tasks', 'detection_scenes', ['scene_id'], ['id'])
    op.drop_column('training_tasks', 'base_architecture')
    op.drop_column('training_tasks', 'set_as_default')
    op.drop_column('training_tasks', 'model_id')
    op.drop_column('training_tasks', 'checkpoint_path')
    op.drop_column('training_tasks', 'last_checkpoint_epoch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_tasks', sa.Column('last_checkpoint_epoch', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='最后保存 checkpoint 的 epoch'))
    op.add_column('training_tasks', sa.Column('checkpoint_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='checkpoint 文件路径'))
    op.add_column('training_tasks', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='关联模型'))
    op.add_column('training_tasks', sa.Column('set_as_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='训练完成后是否自动设为默认版本'))
    op.add_column('training_tasks', sa.Column('base_architecture', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='基础架构'))
    op.drop_constraint(None, 'training_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_training_tasks_scene_id'), table_name='training_tasks')
    op.create_index(op.f('ix_training_tasks_model_id'), 'training_tasks', ['model_id'], unique=False)
    op.drop_column('training_tasks', 'model_name')
    op.drop_column('training_tasks', 'scene_id')
    op.add_column('model_versions', sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'training'::character varying"), autoincrement=False, nullable=True, comment='来源：training/upload/import'))
    op.add_column('model_versions', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='所属模型'))
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.drop_index(op.f('ix_model_versions_scene_id'), table_name='model_versions')
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.drop_column('model_versions', 'model_type')
    op.drop_column('model_versions', 'model_name')
    op.drop_column('model_versions', 'scene_id')
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='模型名称'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='模型描述'),
    sa.Column('base_architecture', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='基础架构：yolov11n/s/m/l/x'),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='模型分类'),
    sa.Column('class_names', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='类别列表'),
    sa.Column('class_names_cn', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='类别中文名映射'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='状态：active/archived'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='创建人'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('models_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('models_pkey')),
    sa.UniqueConstraint('name', name=op.f('models_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_table('scene_models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='场景ID'),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='模型ID'),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否为该场景的默认模型'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('scene_models_model_id_fkey')),
    sa.ForeignKeyConstraint(['scene_id'], ['detection_scenes.id'], name=op.f('scene_models_scene_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scene_models_pkey'))
    )
    op.create_index(op.f('ix_scene_models_scene_id'), 'scene_models', ['scene_id'], unique=False)
    op.create_index(op.f('ix_scene_models_model_id'), 'scene_models', ['model_id'], unique=False)
    # ### end Alembic commands ###
