"""add_status_indexes

Revision ID: ded4aa9bedf1
Revises: a3f2b1c8d901
Create Date: 2026-07-09 01:51:24.575687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded4aa9bedf1'
down_revision: Union[str, Sequence[str], None] = 'a3f2b1c8d901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_sessions_status'), 'chat_sessions', ['status'], unique=False)
    op.create_index('ix_chat_sessions_user_status', 'chat_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_detection_tasks_status'), 'detection_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.alter_column('training_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：pending/running/pausing/paused/completed/failed/cancelled',
               existing_comment='状态：pending/running/completed/failed/cancelled',
               existing_nullable=True)
    op.create_index(op.f('ix_training_tasks_status'), 'training_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_tasks_status'), table_name='training_tasks')
    op.alter_column('training_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：pending/running/completed/failed/cancelled',
               existing_comment='状态：pending/running/pausing/paused/completed/failed/cancelled',
               existing_nullable=True)
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_detection_tasks_status'), table_name='detection_tasks')
    op.drop_index('ix_chat_sessions_user_status', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_status'), table_name='chat_sessions')
    # ### end Alembic commands ###
